version: '3'

services:
  mongo:
    image: mongo:latest
    hostname: mongo
    ports:
      - "27018:27017"

  redis:
    image: redis
    ports:
      - "6379:6379"
    restart: always

  redisui:
    image: marian/rebrow
    ports:
      - "5001:5001"
    restart: always
    links:
      - redis