name: Build/release

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: npm install
      - run: npm run lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.7.0
        with:
          mongodb-version: 4.2

      - name: Start Redis
        uses: supercharge/redis-github-action@1.2.0
        with:
          redis-version: 5

      - run: cd app && yarn install
      - run: cd app && yarn test

  release:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up npm
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install caprover
        run: npm install -g caprover

      - name: Caprover Deploy
        run: caprover deploy -h 'https://captain.captain.sv.ufabcnext.com' -p '${{ secrets.CAPROVER_PASSWORD }}' -b 'master' -a 'api'
