name: Coverage

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    
    env:
      CODECOV_TOKEN: 613992d7-a6fc-4f73-8b0f-bfbe632ff352
      
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16
        
    - name: Install and Run Yarn
      run: npm install -g yarn && cd app && yarn
    
    - name: Install NYC
      run: npm install -D nyc --save-dev -g
    
    - name: Start Docker Containers
      run: cd app && docker-compose -f "docker-compose.yaml" up -d --build
      
    - name: Install Dependendcies
      run: cd app && yarn install
      
    - name: Run Tests and Generate Coverage Report
      run: cd app && nyc npm run test && nyc report --reporter=text-lcov > coverage.lcov
      
    - name: Codecov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        flags: unittests
        files: ./app/coverage.lcov
   
    - name: Stop Docker Containers
      run: cd app && docker-compose -f "docker-compose.yaml" down
